# Generated by Django 4.1.7 on 2023-03-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('montant', models.IntegerField()),
                ('date_AJOUT', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('loyer', 'loyer'), ('manger', 'manger'), ('transport', 'transport'), ('devertissement', 'divertisssemnt')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_AJOUT', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('salaire', 'salaire'), ('Business', 'Business')], max_length=100)),
            ],
        ),
    ]
